from typing import Optional
TEXTS = {
    "ru": {
        "choose_language": "Выбери язык / Choose language",
        "language_saved": "Язык сохранён. Бюрократия победила.",
        "start": "Здарова. Я Вальсон: помогу найти пару на вальс и не устроить социальную катастрофу.",
        "choose_action": "Выбирай, что делаем:",
        "create_profile": "создать / обновить анкету",
        "browse_profiles": "смотреть анкеты",
        "delete_profile": "удалить мою анкету",
        "choose_gender": "Выбирай свой пол. Да, кнопкой. Цивилизация.",
        "gender_girl": "девчонка",
        "gender_boy": "мальчик",
        "choose_gender_button": "Выбери кнопкой: девчонка или мальчик. Импровизация тут не нужна, это не джаз.",
        "enter_name": "Введи своё имя. Настоящее, сценический псевдоним оставим для премьеры.",
        "bad_name": "Имя должно быть от 2 до 40 символов. Одной буквой загадочность не засчитана.",
        "enter_class": "Ты кто и с какого? Например: Л, Фил, Им, Физ",
        "bad_class": "Класс/профиль должен быть от 1 до 20 символов. Сочинения мне тут нужны.",
        "enter_height": "Теперь рост числом. Например: 169. Без «примерно как шкаф».",
        "bad_height_number": "Рост надо числом. Например: 169. Я, к сожалению, не телепат.",
        "bad_height_range": "Введи нормальный рост от сотки до 250. Карликов и великанов я не видела у нас",
        "enter_photo": "Кинь фотку. Желательно такую, где тебя можно узнать без следственного отдела.",
        "bad_photo": "Это не фотка. Кинь именно фото, не стикер и не текст. Да, я придираюсь.",
        "enter_description": "Опиши себя немного: стиль, опыт, что ищешь. Кратко четко смешно..по твоим умственным возможностям.",
        "bad_description_short": "Слишком коротко. Напиши хотя бы пару слов, загадочный ты наш.",
        "bad_description_long": "Слишком длинно. До 500 символов. Толстой бы понял, но моя база данных — нет.",
        "enter_contact": "Кинь ссылку на тг/инсту/вк или юзернейм, где с тобой можно связаться.",
        "bad_contact": "Контакт выглядит странно. Введи нормально, чтобы люди не искали тебя через голубиную почту.",
        "profile_saved": "Анкета сохранена. Теперь ты официально в базе романтической логистики.",
        "profile_deleted": "Твоя анкета удалена. Следов....почти не осталось.",
        "no_profile_to_delete": "Удалять нечего: анкеты нет. Красиво, чисто, пусто.",
        "browse_class": "Какой класс хочешь посмотреть? Например: Л, Фил, Им, Физ",
        "no_profiles": "По этому классу пока нет анкет. Пустыня. Попробуй другой класс.",
        "expired_list": "Список устарел. Выбери класс заново — вечность в Telegram короткая.",
        "change_class": "хочу посмотреть другой класс",
        "page": "Страница {current} из {total}",
        "cm": "см",
        "cancelled": "Окей, окей, отменила. Драма снята с репертуара.",
        "like": "лайк",
        "skip": "скип",
        "liked": "Лайк сохранён.",
        "match": "МЭТЧ. Вы оба лайкнули друг друга.",
        "new_match": "У тебя новый мэтч.",
        "already_liked": "Ты уже лайкал эту анкету.",
        "own_profile": "Свою анкету лайкать нельзя. Самолюбие это хорошо, но нет.",
        "score": "Совместимость: {score}%",
    },
    "en": {
        "choose_language": "Choose language / Выбери язык",
        "language_saved": "Language saved. Bureaucracy has prevailed.",
        "start": "Hi. I am Valson: I help people find waltz partners without turning it into a social incident.",
        "choose_action": "Choose what you wanna do. Please keep the chaos artisanal:",
        "create_profile": "create / update profile",
        "browse_profiles": "browse profiles",
        "delete_profile": "delete my profile",
        "choose_gender": "Choose your gender. With a button. Civilization, allegedly.",
        "gender_girl": "girl",
        "gender_boy": "boy",
        "choose_gender_button": "Choose with a button: girl or boy. Free-form poetry is not supported here.",
        "enter_name": "Enter your name. Your actual one; stage names can wait.",
        "bad_name": "Name must be from 2 to 40 characters. One-letter mystique does not count.",
        "enter_class": "Enter your class/profile. For example: L, Phil, Math, Phys",
        "bad_class": "Class/profile must be from 1 to 20 characters. I def do not need your memoirs.",
        "enter_height": "Enter your height as a number. For example: 169. No “roughly wardrobe-sized”.",
        "bad_height_number": "Height must be a number. For example: 169. Sadly, I am not psychic.",
        "bad_height_range": "Enter a realistic height from 100 to 250. Havent seen dwarves or titans here.",
        "enter_photo": "Send a photo. Preferably one where people can recognize you without forensic reconstruction.",
        "bad_photo": "This is not a photo. Send an actual photo, not a sticker or text. Yes, I am being picky.",
        "enter_description": "Write a short description: style, experience, what you are looking for. Brief, clear (within your intellectual budget).",
        "bad_description_short": "Too short. Give me at least a few words, mysterious creature.",
        "bad_description_long": "Too long. Maximum 500 characters. Tolstoy would understand, but my database won't.",
        "enter_contact": "Send a Telegram/Instagram/VK link or username where people can contact you.",
        "bad_contact": "This contact looks wrong. Enter it properly; carrier pigeons are not integrated.",
        "profile_saved": "Profile saved. You are now in the romantic logistics database.",
        "profile_deleted": "Your profile has been deleted. Almost no trace is left...almost.",
        "no_profile_to_delete": "Nothing to delete: you do not have a profile. Neat, clean, empty.",
        "browse_class": "Which class do you want to browse? For example: L, Phil, Math, Phys",
        "no_profiles": "No profiles for this class yet. A desert. Try another class.",
        "expired_list": "This list has expired. Choose the class again — eternity is short in Telegram.",
        "change_class": "browse another class",
        "page": "Page {current} of {total}",
        "cm": "cm",
        "cancelled": "Cancelled. Drama removed from the program.",
        "like": "like",
        "skip": "skip",
        "liked": "Like saved.",
        "match": "MATCH. You both liked each other.",
        "new_match": "You have a new match.",
        "already_liked": "You already liked this profile.",
        "own_profile": "You cannot like your own profile. Nice try.",
        "score": "Compatibility: {score}%",
    },
}
def t(language: Optional[str], key: str) -> str:
    language = language if language in TEXTS else "ru"
    return TEXTS[language][key]
