from typing import Optional

TEXTS = {
    "ru": {
        "choose_language": "Выбери язык / Choose language",
        "language_saved": "Язык сохранён. Бюрократия победила.",
        "start": "Здарова. Я Вальсон: помогу найти пару на вальс и не устроить социальную катастрофу.",
        "choose_action": "Выбирай, что делаем. Только без хаоса, я сегодня на смене:",
        "create_profile": "создать / обновить анкету",
        "edit_profile": "редактировать анкету",
        "set_prefs": "настроить поиск пары",
        "find_matches": "найти совпадения",
        "browse_profiles": "смотреть анкеты",
        "delete_profile": "удалить мою анкету",
        "choose_gender": "Выбирай свой пол. Да, кнопкой. Цивилизация.",
        "gender_girl": "девчонка",
        "gender_boy": "мальчик",
        "choose_gender_button": "Выбери кнопкой: девчонка или мальчик. Импровизация тут не нужна, это не джаз.",
        "enter_name": "Введи своё имя. Настоящее, сценический псевдоним оставим для премьеры.",
        "bad_name": "Имя должно быть от 2 до 40 символов.",
        "enter_class": "Ты кто и с какого? Например: Л, Фил, Им, Физ",
        "bad_class": "Класс/профиль должен быть от 1 до 20 символов.",
        "enter_height": "Теперь рост числом. Например: 169.",
        "bad_height_number": "Рост надо числом. Например: 169.",
        "bad_height_range": "Введи нормальный рост от 120 до 230.",
        "enter_role": "Роль в танце: lead, follow или both",
        "bad_role": "Напиши lead, follow или both.",
        "enter_experience": "Опыт: beginner/intermediate/advanced или просто своими словами.",
        "bad_experience": "Слишком длинно. До 40 символов.",
        "enter_availability": "Когда удобно репетировать? Например: weekdays, weekends, evenings",
        "bad_availability": "До 100 символов, без романа.",
        "enter_tempo": "Темп, если важно. Например: slow/medium/fast. Можно написать -",
        "enter_goals": "Цель: competition, social или что-то своё. Можно написать -",
        "enter_photo": "Кинь фотку. Желательно такую, где тебя можно узнать.",
        "bad_photo": "Это не фотка. Кинь именно фото, не стикер и не текст.",
        "enter_description": "Опиши себя немного: стиль, опыт, что ищешь.",
        "bad_description_short": "Слишком коротко. Напиши хотя бы пару слов.",
        "bad_description_long": "Слишком длинно. До 500 символов.",
        "enter_contact": "Кинь ссылку на тг/инсту/вк или юзернейм, где с тобой можно связаться.",
        "bad_contact": "Контакт выглядит странно. Введи нормально.",
        "profile_saved": "Анкета сохранена.",
        "profile_deleted": "Твоя анкета удалена.",
        "no_profile_to_delete": "Удалять нечего: анкеты нет.",
        "browse_class": "Какой класс хочешь посмотреть? Например: Л, Фил, Им, Физ",
        "no_profiles": "По этому классу пока нет анкет. Попробуй другой класс.",
        "expired_list": "Список устарел. Выбери заново.",
        "change_class": "хочу посмотреть другой класс",
        "page": "Страница {current} из {total}",
        "cm": "см",
        "cancelled": "Окей, отменил.",
        "pref_class": "Класс/уровень, который ищешь? Например: Л, Фил, Им, Физ",
        "pref_role": "Кого ищешь по роли: lead, follow или both",
        "pref_height": "Диапазон роста через дефис. Например: 160-180",
        "bad_height_range_pref": "Нужен диапазон типа 160-180.",
        "pref_saved": "Настройки поиска сохранены.",
        "need_profile": "Сначала создай анкету.",
        "need_prefs": "Сначала настрой поиск пары.",
        "no_matches": "Пока нормальных совпадений нет.",
        "match_reasons": "Совпало: {reasons}",
        "score": "Совпадение: {score}%",
        "edit_choose": "Что меняем?",
        "edit_value": "Новое значение:",
        "edit_saved": "Изменила.",
        "bad_edit_field": "Такое поле не редактирую.",
    },
    "en": {
        "choose_language": "Choose language / Выбери язык",
        "language_saved": "Language saved. Bureaucracy has prevailed.",
        "start": "Hi. I am Valson: I help people find waltz partners without turning it into a social incident.",
        "choose_action": "Choose what you want to do:",
        "create_profile": "create / update profile",
        "edit_profile": "edit profile",
        "set_prefs": "set match preferences",
        "find_matches": "find matches",
        "browse_profiles": "browse profiles",
        "delete_profile": "delete my profile",
        "choose_gender": "Choose your gender. With a button.",
        "gender_girl": "girl",
        "gender_boy": "boy",
        "choose_gender_button": "Choose with a button: girl or boy.",
        "enter_name": "Enter your name.",
        "bad_name": "Name must be from 2 to 40 characters.",
        "enter_class": "Enter your class/profile. For example: L, Phil, Math, Phys",
        "bad_class": "Class/profile must be from 1 to 20 characters.",
        "enter_height": "Enter your height as a number. For example: 169.",
        "bad_height_number": "Height must be a number. For example: 169.",
        "bad_height_range": "Enter a realistic height from 120 to 230.",
        "enter_role": "Dance role: lead, follow or both",
        "bad_role": "Write lead, follow or both.",
        "enter_experience": "Experience: beginner/intermediate/advanced or your own words.",
        "bad_experience": "Too long. Up to 40 chars.",
        "enter_availability": "When can you practice? Example: weekdays, weekends, evenings",
        "bad_availability": "Up to 100 chars.",
        "enter_tempo": "Tempo, if it matters: slow/medium/fast. Or write -",
        "enter_goals": "Goal: competition, social or your own. Or write -",
        "enter_photo": "Send a photo.",
        "bad_photo": "This is not a photo. Send an actual photo.",
        "enter_description": "Write a short description: style, experience, what you want.",
        "bad_description_short": "Too short. Write at least a few words.",
        "bad_description_long": "Too long. Maximum 500 characters.",
        "enter_contact": "Send a Telegram/Instagram/VK link or username.",
        "bad_contact": "This contact looks wrong. Enter it properly.",
        "profile_saved": "Profile saved.",
        "profile_deleted": "Your profile has been deleted.",
        "no_profile_to_delete": "Nothing to delete: you do not have a profile.",
        "browse_class": "Which class do you want to browse? For example: L, Phil, Math, Phys",
        "no_profiles": "No profiles for this class yet. Try another class.",
        "expired_list": "This list has expired. Choose again.",
        "change_class": "browse another class",
        "page": "Page {current} of {total}",
        "cm": "cm",
        "cancelled": "Cancelled.",
        "pref_class": "Preferred class/level? Example: L, Phil, Math, Phys",
        "pref_role": "Preferred partner role: lead, follow or both",
        "pref_height": "Height range with dash. Example: 160-180",
        "bad_height_range_pref": "Use a range like 160-180.",
        "pref_saved": "Match preferences saved.",
        "need_profile": "Create a profile first.",
        "need_prefs": "Set match preferences first.",
        "no_matches": "No good matches yet.",
        "match_reasons": "Matched: {reasons}",
        "score": "Match: {score}%",
        "edit_choose": "What do you want to edit?",
        "edit_value": "New value:",
        "edit_saved": "Updated.",
        "bad_edit_field": "I do not edit that field.",
    },
}

def t(language: Optional[str], key: str) -> str:
    language = language if language in TEXTS else "ru"
    return TEXTS[language][key]
