TEXTS = {
    "ru": {
        "choose_language": "Выбери язык / Choose language",
        "language_saved": "Язык сохранён.",
        "start": "Здарова. Я помогу найти пару на вальс.",
        "choose_action": "Выбирай, что делаем:",
        "create_profile": "создать / обновить анкету",
        "browse_profiles": "смотреть анкеты",
        "delete_profile": "удалить мою анкету",
        "choose_gender": "Выбирай свой пол",
        "gender_girl": "девчонка",
        "gender_boy": "мальчик",
        "choose_gender_button": "Выбери кнопкой: девчонка или мальчик",
        "enter_name": "Введи свое имя",
        "bad_name": "Имя должно быть от 2 до 40 символов",
        "enter_class": "Ты кто с какого? Например: Л, Фил, Им, Физ",
        "bad_class": "Класс/профиль должен быть от 1 до 20 символов",
        "enter_height": "Теперь свой рост числом. Например: 169",
        "bad_height_number": "Рост надо числом. Например: 169",
        "bad_height_range": "Введи нормальный рост от 120 до 230",
        "enter_photo": "Кинь фотку",
        "bad_photo": "Это не фотка. Кинь именно фото, не стикер и не текст.",
        "enter_description": "Опиши себя немного",
        "bad_description_short": "Слишком коротко. Напиши хотя бы пару слов",
        "bad_description_long": "Слишком длинно. До 500 символов",
        "enter_contact": "Кинь ссылку на тг/инсту/вк или юзернейм, где с тобой можно связаться",
        "bad_contact": "Контакт выглядит странно. Введи нормально",
        "profile_saved": "Анкета сохранена.",
        "profile_deleted": "Твоя анкета удалена.",
        "browse_class": "Какой класс хочешь посмотреть? Например: Л, Фил, Им, Физ",
        "no_profiles": "По этому классу пока нет анкет. Попробуй другой класс.",
        "expired_list": "Список устарел. Выбери класс заново.",
        "change_class": "хочу посмотреть другой класс",
        "page": "Страница {current} из {total}",
    },
    "en": {
        "choose_language": "Choose language / Выбери язык",
        "language_saved": "Language saved.",
        "start": "Hi. I can help you find a waltz partner.",
        "choose_action": "Choose what you want to do:",
        "create_profile": "create / update profile",
        "browse_profiles": "browse profiles",
        "delete_profile": "delete my profile",
        "choose_gender": "Choose your gender",
        "gender_girl": "girl",
        "gender_boy": "boy",
        "choose_gender_button": "Choose with a button: girl or boy",
        "enter_name": "Enter your name",
        "bad_name": "Name must be from 2 to 40 characters",
        "enter_class": "Enter your class/profile. For example: L, Phil, Math, Phys",
        "bad_class": "Class/profile must be from 1 to 20 characters",
        "enter_height": "Enter your height as a number. For example: 169",
        "bad_height_number": "Height must be a number. For example: 169",
        "bad_height_range": "Enter a realistic height from 120 to 230",
        "enter_photo": "Send a photo",
        "bad_photo": "This is not a photo. Send an actual photo, not a sticker or text.",
        "enter_description": "Write a short description",
        "bad_description_short": "Too short. Write at least a few words",
        "bad_description_long": "Too long. Maximum 500 characters",
        "enter_contact": "Send a Telegram/Instagram/VK link or username where people can contact you",
        "bad_contact": "This contact looks wrong. Enter it properly",
        "profile_saved": "Profile saved.",
        "profile_deleted": "Your profile has been deleted.",
        "browse_class": "Which class do you want to browse? For example: L, Phil, Math, Phys",
        "no_profiles": "No profiles for this class yet. Try another class.",
        "expired_list": "This list has expired. Choose the class again.",
        "change_class": "browse another class",
        "page": "Page {current} of {total}",
    },
}


def t(language: str | None, key: str) -> str:
    language = language if language in TEXTS else "ru"
    return TEXTS[language][key]
